# Generated by Django 5.2.6 on 2025-10-14 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_productlist_image_url_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='productlist',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='colour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='colour', to='products_app.colour'),
            preserve_default=False,
        ),
    ]
