# Generated by Django 5.2.6 on 2025-10-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_orderstatus_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'Order Status'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_description',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
