# Generated by Django 5.2.6 on 2025-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0009_category_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=150)),
                ('image', models.URLField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
