# Generated by Django 5.2.6 on 2025-10-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0010_seasonchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='name_entry',
            field=models.BooleanField(default=False),
        ),
    ]
