# Generated by Django 5.2.6 on 2025-10-19 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0012_order_order_number_orderitem_personalization_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='personalization_name',
            new_name='customer_input_name',
        ),
    ]
