# Generated by Django 5.2.6 on 2025-10-19 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0013_rename_personalization_name_orderitem_customer_input_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer_input_name',
            new_name='personalization_name',
        ),
    ]
