# Generated by Django 5.2.6 on 2025-10-19 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0014_rename_customer_input_name_orderitem_personalization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='products_app.colour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status', to='products_app.orderstatus'),
        ),
    ]
