# Generated by Django 5.2.6 on 2025-10-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0015_orderitem_color_alter_order_customer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
    ]
