# Generated by Django 5.2.6 on 2025-10-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0017_orderitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
    ]
