# Generated by Django 5.2.6 on 2025-10-19 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0019_orderitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.AddField(
            model_name='colour',
            name='image',
            field=models.URLField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_options', to='products_app.colour')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_options', to='products_app.productlist')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products_app.productcolour'),
        ),
        migrations.AddConstraint(
            model_name='productcolour',
            constraint=models.UniqueConstraint(fields=('product', 'colour'), name='uniq_product_colour'),
        ),
    ]
