# Generated by Django 5.2.6 on 2025-10-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0020_remove_orderitem_color_colour_image_productcolour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colour',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productcolour',
            name='price_delta',
        ),
        migrations.RemoveField(
            model_name='productcolour',
            name='stock',
        ),
    ]
