# Generated by Django 5.2.6 on 2025-10-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0021_remove_colour_image_remove_productcolour_price_delta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='colour',
        ),
    ]
