# Generated by Django 5.2.6 on 2025-10-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0022_remove_productlist_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productcolour',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='seasonchange',
            name='image',
            field=models.URLField(),
        ),
    ]
