# Generated by Django 5.2.6 on 2025-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0024_alter_category_image_alter_productcolour_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='personalization_name',
            new_name='personalization_name_ar',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='personalization_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='personalization_option',
            field=models.CharField(choices=[('none', 'None'), ('en', 'English only'), ('ar', 'Arabic only'), ('both', 'English + Arabic')], default='none', max_length=10),
        ),
    ]
