# Generated by Django 5.2.6 on 2025-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0025_rename_personalization_name_orderitem_personalization_name_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='name_entry',
            new_name='arabic_name_entry_only',
        ),
        migrations.AddField(
            model_name='productlist',
            name='both_name_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='english_name_entry_only',
            field=models.BooleanField(default=False),
        ),
    ]
