# Generated by Django 5.2.6 on 2025-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0026_rename_name_entry_productlist_arabic_name_entry_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='single_language_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='two_language_price',
            field=models.FloatField(default=0),
        ),
    ]
