# Generated by Django 5.2.6 on 2025-10-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0027_productlist_single_language_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='babeloo_font',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='creamy_font',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='goudy_font',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='naskh_hadith_font',
            field=models.BooleanField(default=False),
        ),
    ]
