# Generated by Django 5.2.6 on 2025-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0028_productlist_babeloo_font_productlist_creamy_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='note',
            field=models.CharField(blank=True, null=True),
        ),
    ]
