# Generated by Django 5.2.6 on 2025-10-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0029_productlist_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='personalization_font_ar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='personalization_font_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
